# Template for yaml config


# Add main port and volume in config["main"]

main: {
  port: 8000,             #int
  volume: stuff,          #str
}


# For each microservice in your project, create a key inside the micros dictionary that is the microservice name. Each microservice can have 3 key/value pairs.
# apps - a list of app names. To keep name_rest in the list, pass default in
# project - only add if changing name from default name_project
micros: {
  micro_name: {
    apps: [app1, app2, app3, app4, ect...],
    project: some_name,
    port: 8100,
    poller: True,
  },
}


# At config["queues"], add queues to any microservices that need them. Keys will be the consumers. Each value will be a list containing the producer microservice@app
queues: {
    app1: ["micro2@app1", "micro3@default"],
    app2: ["micro1@app2"],
    app3: ["micro1@app1"]
}